import FujiPic from "../../../../public/Icon/Common/report.png";

export const data_N1 = [
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Stoper Lock Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 2,
    img: FujiPic,
    Page_Name: "TITLE2",
    link: "",
    path: "",
    desc: "DESC2",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 3,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 4,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Stoper Lock Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 2,
    img: FujiPic,
    Page_Name: "TITLE2",
    link: "",
    path: "",
    desc: "DESC2",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 3,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 4,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Stoper Lock Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 2,
    img: FujiPic,
    Page_Name: "TITLE2",
    link: "",
    path: "",
    desc: "DESC2",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 3,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 4,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Stoper Lock Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 2,
    img: FujiPic,
    Page_Name: "TITLE2",
    link: "",
    path: "",
    desc: "DESC2",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 3,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 4,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
];

export const data_N1_2 = [
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Stoper Lock Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 2,
    img: FujiPic,
    Page_Name: "TITLE2",
    link: "",
    path: "",
    desc: "DESC2",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 3,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 4,
    img: FujiPic,
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
];

export const data_A1 = [
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Stoper Lock Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 2,
    img: "https://www.techmoblog.com/uploads/content_images/201907/img_1564135077_6209855ea8da.jpg",
    Page_Name: "SMT MOT",
    link: "",
    path: "",
    desc: "DESC2",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 3,
    img: "https://positioningmag.com/wp-content/uploads/2019/08/open_applespecialnew1.jpg",
    Page_Name: "SMT BE",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 4,
    img: "https://www.iphone-droid.net/wp-content/uploads/2021/03/how-to-type-apple-logo-on-iphone.png",
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Stoper Lock Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 5,
    img: "https://i.ebayimg.com/images/g/eS4AAOSwPHJdDUJm/s-l1200.webp",
    Page_Name: "TITLE2",
    link: "",
    path: "",
    desc: "DESC2",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 6,
    img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202109/apple_ar.jpg?size=690:388",
    Page_Name: "TITLE3",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Stoper Lock Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  // {
  //   id: 2,
  //   img: "https://www.techmoblog.com/uploads/content_images/201907/img_1564135077_6209855ea8da.jpg",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 3,
  //   img: "https://positioningmag.com/wp-content/uploads/2019/08/open_applespecialnew1.jpg",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 4,
  //   img: "https://www.iphone-droid.net/wp-content/uploads/2021/03/how-to-type-apple-logo-on-iphone.png",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 5,
  //   img: "https://i.ebayimg.com/images/g/eS4AAOSwPHJdDUJm/s-l1200.webp",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 6,
  //   img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202109/apple_ar.jpg?size=690:388",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 1,
  //   img: FujiPic,
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 2,
  //   img: "https://www.techmoblog.com/uploads/content_images/201907/img_1564135077_6209855ea8da.jpg",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 3,
  //   img: "https://positioningmag.com/wp-content/uploads/2019/08/open_applespecialnew1.jpg",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 4,
  //   img: "https://www.iphone-droid.net/wp-content/uploads/2021/03/how-to-type-apple-logo-on-iphone.png",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 5,
  //   img: "https://i.ebayimg.com/images/g/eS4AAOSwPHJdDUJm/s-l1200.webp",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 6,
  //   img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202109/apple_ar.jpg?size=690:388",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
];

export const data_A2 = [
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "LPI Screen Tension",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 2,
    img: "https://www.techmoblog.com/uploads/content_images/201907/img_1564135077_6209855ea8da.jpg",
    Page_Name: "LPI CHART",
    link: "",
    path: "",
    desc: "DESC2",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  {
    id: 3,
    img: "https://positioningmag.com/wp-content/uploads/2019/08/open_applespecialnew1.jpg",
    Page_Name: "PLI Monitor",
    link: "",
    path: "",
    desc: "DESC3",
    desc_2: "Example Card 1",
    desc_3: "Example Card 1",
  },
  // {
  //   id: 4,
  //   img: "https://www.iphone-droid.net/wp-content/uploads/2021/03/how-to-type-apple-logo-on-iphone.png",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 5,
  //   img: "https://i.ebayimg.com/images/g/eS4AAOSwPHJdDUJm/s-l1200.webp",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 6,
  //   img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202109/apple_ar.jpg?size=690:388",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 1,
  //   img: FujiPic,
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 2,
  //   img: "https://www.techmoblog.com/uploads/content_images/201907/img_1564135077_6209855ea8da.jpg",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 3,
  //   img: "https://positioningmag.com/wp-content/uploads/2019/08/open_applespecialnew1.jpg",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 4,
  //   img: "https://www.iphone-droid.net/wp-content/uploads/2021/03/how-to-type-apple-logo-on-iphone.png",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 5,
  //   img: "https://i.ebayimg.com/images/g/eS4AAOSwPHJdDUJm/s-l1200.webp",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 6,
  //   img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202109/apple_ar.jpg?size=690:388",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 1,
  //   img: FujiPic,
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 2,
  //   img: "https://www.techmoblog.com/uploads/content_images/201907/img_1564135077_6209855ea8da.jpg",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 3,
  //   img: "https://positioningmag.com/wp-content/uploads/2019/08/open_applespecialnew1.jpg",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 4,
  //   img: "https://www.iphone-droid.net/wp-content/uploads/2021/03/how-to-type-apple-logo-on-iphone.png",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 5,
  //   img: "https://i.ebayimg.com/images/g/eS4AAOSwPHJdDUJm/s-l1200.webp",
  //   Page_Name: "TITLE2",
  //   link: "",
  //   path: "",
  //   desc: "DESC2",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
  // {
  //   id: 6,
  //   img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202109/apple_ar.jpg?size=690:388",
  //   Page_Name: "TITLE3",
  //   link: "",
  //   path: "",
  //   desc: "DESC3",
  //   desc_2: "Example Card 1",
  //   desc_3: "Example Card 1",
  // },
];

export const data_hr_Kanda = [
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Man Power Working Input",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Man Power Working Status",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
  {
    id: 1,
    img: FujiPic,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Man Power Working HR",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Stopper Lock Status",
  },
];
