import AppIMG from "../../../public/Icon/Common/app-store.png";
import App2IMG from "../../../public/Icon/Common/photos.png";
import App3IMG from "../../../public/Icon/Common/tinder.png";
import App4IMG from "../../../public/Icon/Common/spotify.png";
import App5IMG from "../../../public/Icon/Common/lemon8.png";
import App6IMG from "../../../public/Icon/Common/youtube.png";
import App7IMG from "../../../public/Icon/Common/linkedin.png";
import App8IMG from "../../../public/Icon/Common/netflix.png";
import App9IMG from "../../../public/Icon/Common/jobthai.png";

export const data_N1 = [
  {
    id: 1,
    img: AppIMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "App Store",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is App Store",
  },
  {
    id: 1,
    img: App2IMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Gallery",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Gallery",
  },
  {
    id: 1,
    img: App3IMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Tinder",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is Dating app",
  },
  {
    id: 1,
    img: App4IMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Spotify",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is music app",
  },
  {
    id: 1,
    img: App5IMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Lemon8",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is review app",
  },
  {
    id: 1,
    img: App6IMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Youtube",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is video app",
  },
  {
    id: 1,
    img: App7IMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Linkedin",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is professional app",
  },
  {
    id: 1,
    img: App8IMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Netflix",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is movie app",
  },
  {
    id: 1,
    img: App9IMG,
    link: "http://10.17.66.242",
    path: "/stopper-lock-status/stopper-lock-status",
    Page_Name: "Jobthai",
    desc: "SMART A1",
    desc_2: "Link",
    desc_3: "This is job app",
  },
  // {
  //   id: 1,
  //   img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVxOg90a26Hbzoyv2ZaX9Ey1OZkO4-wCtDqQq6q5gZuKQctR6cNkNjp11HC72mWv3kE6A&usqp=CAU",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 1,
  //   img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVxOg90a26Hbzoyv2ZaX9Ey1OZkO4-wCtDqQq6q5gZuKQctR6cNkNjp11HC72mWv3kE6A&usqp=CAU",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 1,
  //   img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVxOg90a26Hbzoyv2ZaX9Ey1OZkO4-wCtDqQq6q5gZuKQctR6cNkNjp11HC72mWv3kE6A&usqp=CAU",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
  // {
  //   id: 1,
  //   img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVxOg90a26Hbzoyv2ZaX9Ey1OZkO4-wCtDqQq6q5gZuKQctR6cNkNjp11HC72mWv3kE6A&usqp=CAU",
  //   link: "http://10.17.66.242",
  //   path: "/stopper-lock-status/stopper-lock-status",
  //   Page_Name: "Stoper Lock Status",
  //   desc: "SMART A1",
  //   desc_2: "Link",
  //   desc_3: "This is Stopper Lock Status",
  // },
];
